### ISSUE TITLE
VPC ACLs, not WAF ACLs

### ISSUE THREAD

**Issue by cariaso** [anthonymartin/aws-acl-fail2ban#1]
I believe the bottom of the readme should be changed from
`action = aws-acl-action`
to
`action = aws-acl`

It seems this uses VPC ACLs inbound rules
( https://us-east-1.console.aws.amazon.com/vpc/home?region=us-east-1#acls: )
initially I thought it was using WAF webacls
( https://console.aws.amazon.com/waf/home?region=us-east-1#/webacls )
and if so, the VPC ACLs seem to be limited to 20 rules. Please confirm and perhaps clarify this in the documentation.

It seems possible to update it so that it does use waf filtering, and if so that would seem to be effectively unlimited. Is that something you would consider supporting?

**Comment by anthonymartin** [comment]
I've updated the readme to update the action parameter as you suggested. 

You are right that this is using VPC ACLs and not WAF web rules. WAF requires much more custom setup and this setup wouldn't be as easily translatable if it were using WAF. Additionally the 20 rule constraint with VPC NACLs is not so bad. Fail2ban / this code removes rules from the NACLs list so it's rare for the ruleset to be maxed out unless you are running a massive site. This is not meant as a comprehensive DDoS protection - it's meant to act as a layer of protection within a broader DoS protection architecture. 

Thanks for your comments.
