### ISSUE TITLE
Similar thing for NginX

### ISSUE THREAD

**Issue by supersun1** [anthonymartin/aws-acl-fail2ban#2]
Are you guys planning on implement a similar (or already existing one) for NginX?

Just realized I can write my own :P LOL

**Comment by anthonymartin** [comment]
It might actually work if you change line 6 here https://github.com/anthonymartin/aws-acl-fail2ban/blob/master/fail2ban/jail.local.example to the path of the nginx log file. Can you give that a try and kindly report your findings? If it works, I can update the package and documentation.  If it doesn't work I might be able to easily support it.

**Comment by florianajir** [comment]
@supersun1 Have you tried ?
